
package com.ticketnetwork.webservices2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TNServicesStringInputsHttpGet", targetNamespace = "http://webservices2.ticketnetwork.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TNServicesStringInputsHttpGet {


    /**
     * 
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfCreditCardType
     */
    @WebMethod(operationName = "GetCreditCardTypes")
    @WebResult(name = "ArrayOfCreditCardType", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public ArrayOfCreditCardType getCreditCardTypes(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID);

    /**
     * 
     * @param websiteConfigID
     * @param ticketGroupID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfCreditCardType
     */
    @WebMethod(operationName = "GetAcceptedCreditCardTypes")
    @WebResult(name = "ArrayOfCreditCardType", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public ArrayOfCreditCardType getAcceptedCreditCardTypes(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ticketGroupID")
        String ticketGroupID);

    /**
     * 
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfCategory
     */
    @WebMethod(operationName = "GetCategories")
    @WebResult(name = "ArrayOfCategory", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public ArrayOfCategory getCategories(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID);

    /**
     * 
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfCategory
     */
    @WebMethod(operationName = "GetCategoriesMasterList")
    @WebResult(name = "ArrayOfCategory", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public ArrayOfCategory getCategoriesMasterList(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID);

    /**
     * 
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfCountry
     */
    @WebMethod(operationName = "GetCountries")
    @WebResult(name = "ArrayOfCountry", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public ArrayOfCountry getCountries(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID);

    /**
     * 
     * @param countryID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.Country
     */
    @WebMethod(operationName = "GetCountryByID")
    @WebResult(name = "Country", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public Country getCountryByID(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "countryID")
        String countryID);

    /**
     * 
     * @param performerName
     * @param eventDate
     * @param grandchildCategoryID
     * @param onlyMine
     * @param sortDescending
     * @param endDate
     * @param beginDate
     * @param performerID
     * @param stateProvince
     * @param nearZip
     * @param websiteConfigID
     * @param venueName
     * @param numberOfEvents
     * @param noPerformers
     * @param parentCategoryID
     * @param childCategoryID
     * @param lowPrice
     * @param stateProvinceID
     * @param eventID
     * @param sortColumn
     * @param eventName
     * @param modificationDate
     * @param highPrice
     * @param cityZip
     * @param mandatoryCreditCard
     * @param venueID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfEvent
     */
    @WebMethod(operationName = "GetEvents")
    @WebResult(name = "ArrayOfEvent", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public ArrayOfEvent getEvents(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "numberOfEvents")
        String numberOfEvents,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "eventID")
        String eventID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "eventName")
        String eventName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "eventDate")
        String eventDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "beginDate")
        String beginDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "endDate")
        String endDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "venueID")
        String venueID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "venueName")
        String venueName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "stateProvince")
        String stateProvince,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "stateProvinceID")
        String stateProvinceID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "cityZip")
        String cityZip,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nearZip")
        String nearZip,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "parentCategoryID")
        String parentCategoryID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "childCategoryID")
        String childCategoryID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "grandchildCategoryID")
        String grandchildCategoryID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "performerID")
        String performerID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "performerName")
        String performerName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "noPerformers")
        String noPerformers,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "lowPrice")
        String lowPrice,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "highPrice")
        String highPrice,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "sortColumn")
        String sortColumn,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "sortDescending")
        String sortDescending,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "mandatoryCreditCard")
        String mandatoryCreditCard,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "modificationDate")
        String modificationDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "onlyMine")
        String onlyMine);

    /**
     * 
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfEventPerformer
     */
    @WebMethod(operationName = "GetEventPerformers")
    @WebResult(name = "ArrayOfEventPerformer", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public ArrayOfEventPerformer getEventPerformers(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID);

    /**
     * 
     * @param grandchildCategoryID
     * @param hasEvent
     * @param parentCategoryID
     * @param childCategoryID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfPerformer
     */
    @WebMethod(operationName = "GetPerformerByCategory")
    @WebResult(name = "ArrayOfPerformer", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public ArrayOfPerformer getPerformerByCategory(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "parentCategoryID")
        String parentCategoryID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "childCategoryID")
        String childCategoryID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "grandchildCategoryID")
        String grandchildCategoryID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "hasEvent")
        String hasEvent);

    /**
     * 
     * @param websiteConfigID
     * @param promoCode
     * @return
     *     returns com.ticketnetwork.webservices2.Promo
     */
    @WebMethod(operationName = "GetPromo")
    @WebResult(name = "Promo", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public Promo getPromo(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "promoCode")
        String promoCode);

    /**
     * 
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfReferralType
     */
    @WebMethod(operationName = "GetReferralTypes")
    @WebResult(name = "ArrayOfReferralType", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public ArrayOfReferralType getReferralTypes(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID);

    /**
     * 
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfAddressType
     */
    @WebMethod(operationName = "GetAddressTypes")
    @WebResult(name = "ArrayOfAddressType", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public ArrayOfAddressType getAddressTypes(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID);

    /**
     * 
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfPhoneType
     */
    @WebMethod(operationName = "GetPhoneTypes")
    @WebResult(name = "ArrayOfPhoneType", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public ArrayOfPhoneType getPhoneTypes(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID);

    /**
     * 
     * @param websiteConfigID
     * @param ticketGroupID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfShippingMethod
     */
    @WebMethod(operationName = "GetShippingMethods")
    @WebResult(name = "ArrayOfShippingMethod", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public ArrayOfShippingMethod getShippingMethods(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ticketGroupID")
        String ticketGroupID);

    /**
     * 
     * @param parentCategoryID
     * @param childCategoryID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfCategory
     */
    @WebMethod(operationName = "GetSublevelCategories")
    @WebResult(name = "ArrayOfCategory", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public ArrayOfCategory getSublevelCategories(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "parentCategoryID")
        String parentCategoryID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "childCategoryID")
        String childCategoryID);

    /**
     * 
     * @param sortColumn
     * @param eventID
     * @param numberOfRecords
     * @param sortDescending
     * @param requestedSplit
     * @param websiteConfigID
     * @param highPrice
     * @param lowPrice
     * @param mandatoryCreditCard
     * @param ticketGroupID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfTicketGroup
     */
    @WebMethod(operationName = "GetTickets")
    @WebResult(name = "ArrayOfTicketGroup", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public ArrayOfTicketGroup getTickets(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "numberOfRecords")
        String numberOfRecords,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "eventID")
        String eventID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "lowPrice")
        String lowPrice,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "highPrice")
        String highPrice,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ticketGroupID")
        String ticketGroupID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "mandatoryCreditCard")
        String mandatoryCreditCard,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "requestedSplit")
        String requestedSplit,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "sortColumn")
        String sortColumn,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "sortDescending")
        String sortDescending);

    /**
     * 
     * @param websiteConfigID
     * @param venueID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfVenue
     */
    @WebMethod(operationName = "GetVenue")
    @WebResult(name = "ArrayOfVenue", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public ArrayOfVenue getVenue(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "venueID")
        String venueID);

    /**
     * 
     * @param websiteConfigID
     * @param venueID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfVenueConfiguration
     */
    @WebMethod(operationName = "GetVenueConfigurations")
    @WebResult(name = "ArrayOfVenueConfiguration", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public ArrayOfVenueConfiguration getVenueConfigurations(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "venueID")
        String venueID);

    /**
     * 
     * @param grandchildCategoryID
     * @param numReturned
     * @param parentCategoryID
     * @param childCategoryID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfPerformerPercent
     */
    @WebMethod(operationName = "GetHighInventoryPerformers")
    @WebResult(name = "ArrayOfPerformerPercent", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public ArrayOfPerformerPercent getHighInventoryPerformers(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "numReturned")
        String numReturned,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "parentCategoryID")
        String parentCategoryID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "childCategoryID")
        String childCategoryID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "grandchildCategoryID")
        String grandchildCategoryID);

    /**
     * 
     * @param grandchildCategoryID
     * @param numReturned
     * @param parentCategoryID
     * @param childCategoryID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfPerformerPercent
     */
    @WebMethod(operationName = "GetHighSalesPerformers")
    @WebResult(name = "ArrayOfPerformerPercent", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public ArrayOfPerformerPercent getHighSalesPerformers(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "numReturned")
        String numReturned,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "parentCategoryID")
        String parentCategoryID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "childCategoryID")
        String childCategoryID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "grandchildCategoryID")
        String grandchildCategoryID);

    /**
     * 
     * @param creditCardID
     * @param creditCardTypeID
     * @param customerID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfCreditCard
     */
    @WebMethod(operationName = "GetCreditCard")
    @WebResult(name = "ArrayOfCreditCard", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public ArrayOfCreditCard getCreditCard(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "creditCardID")
        String creditCardID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "customerID")
        String customerID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "creditCardTypeID")
        String creditCardTypeID);

    /**
     * 
     * @param secNumber
     * @param expiresMonth
     * @param number
     * @param customerID
     * @param websiteConfigID
     * @param nameDisplayed
     * @param expiresYear
     * @return
     *     returns com.ticketnetwork.webservices2.CreditCard
     */
    @WebMethod(operationName = "CreateCreditCard")
    @WebResult(name = "CreditCard", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public CreditCard createCreditCard(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "customerID")
        String customerID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "number")
        String number,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "secNumber")
        String secNumber,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nameDisplayed")
        String nameDisplayed,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "expiresMonth")
        String expiresMonth,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "expiresYear")
        String expiresYear);

    /**
     * 
     * @param secNumber
     * @param expiresMonth
     * @param number
     * @param customerID
     * @param websiteConfigID
     * @param nameDisplayed
     * @param expiresYear
     * @return
     *     returns com.ticketnetwork.webservices2.CreditCard
     */
    @WebMethod(operationName = "UpdateCreditCard")
    @WebResult(name = "CreditCard", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public CreditCard updateCreditCard(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "customerID")
        String customerID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "number")
        String number,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "secNumber")
        String secNumber,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nameDisplayed")
        String nameDisplayed,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "expiresMonth")
        String expiresMonth,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "expiresYear")
        String expiresYear);

    /**
     * 
     * @param number
     * @param websiteConfigID
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "IsCreditCardNumberValid")
    @WebResult(name = "boolean", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public boolean isCreditCardNumberValid(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "number")
        String number);

    /**
     * 
     * @param phoneTypeID
     * @param phoneID
     * @param customerID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfPhone
     */
    @WebMethod(operationName = "GetPhone")
    @WebResult(name = "ArrayOfPhone", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public ArrayOfPhone getPhone(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "phoneID")
        String phoneID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "customerID")
        String customerID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "phoneTypeID")
        String phoneTypeID);

    /**
     * 
     * @param phoneNumber
     * @param displayOrder
     * @param phoneTypeID
     * @param customerID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.Phone
     */
    @WebMethod(operationName = "CreatePhone")
    @WebResult(name = "Phone", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public Phone createPhone(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "customerID")
        String customerID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "phoneNumber")
        String phoneNumber,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "phoneTypeID")
        String phoneTypeID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "displayOrder")
        String displayOrder);

    /**
     * 
     * @param phoneNumber
     * @param displayOrder
     * @param phoneTypeID
     * @param customerID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.Phone
     */
    @WebMethod(operationName = "UpdatePhone")
    @WebResult(name = "Phone", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public Phone updatePhone(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "customerID")
        String customerID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "phoneNumber")
        String phoneNumber,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "phoneTypeID")
        String phoneTypeID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "displayOrder")
        String displayOrder);

    /**
     * 
     * @param addressTypeID
     * @param customerID
     * @param addressID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfAddress
     */
    @WebMethod(operationName = "GetAddress")
    @WebResult(name = "ArrayOfAddress", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public ArrayOfAddress getAddress(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "addressID")
        String addressID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "customerID")
        String customerID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "addressTypeID")
        String addressTypeID);

    /**
     * 
     * @param addressTypeID
     * @param stateProvAbbr
     * @param street2
     * @param street1
     * @param countryID
     * @param contactName
     * @param zipCode
     * @param customerID
     * @param websiteConfigID
     * @param country
     * @param city
     * @return
     *     returns com.ticketnetwork.webservices2.Address
     */
    @WebMethod(operationName = "CreateAddress")
    @WebResult(name = "Address", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public Address createAddress(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "customerID")
        String customerID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "contactName")
        String contactName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "street1")
        String street1,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "street2")
        String street2,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "city")
        String city,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "zipCode")
        String zipCode,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "stateProvAbbr")
        String stateProvAbbr,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "country")
        String country,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "countryID")
        String countryID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "addressTypeID")
        String addressTypeID);

    /**
     * 
     * @param addressTypeID
     * @param stateProvAbbr
     * @param street2
     * @param street1
     * @param countryID
     * @param contactName
     * @param zipCode
     * @param customerID
     * @param websiteConfigID
     * @param country
     * @param city
     * @return
     *     returns com.ticketnetwork.webservices2.Address
     */
    @WebMethod(operationName = "UpdateAddress")
    @WebResult(name = "Address", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public Address updateAddress(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "customerID")
        String customerID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "contactName")
        String contactName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "street1")
        String street1,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "street2")
        String street2,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "city")
        String city,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "zipCode")
        String zipCode,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "stateProvAbbr")
        String stateProvAbbr,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "country")
        String country,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "countryID")
        String countryID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "addressTypeID")
        String addressTypeID);

    /**
     * 
     * @param customerID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.Customer
     */
    @WebMethod(operationName = "GetCustomerByID")
    @WebResult(name = "Customer", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public Customer getCustomerByID(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "customerID")
        String customerID);

    /**
     * 
     * @param lastName
     * @param email
     * @param notes
     * @param firstName
     * @param websiteConfigID
     * @param password
     * @return
     *     returns com.ticketnetwork.webservices2.Customer
     */
    @WebMethod(operationName = "CreateCustomer")
    @WebResult(name = "Customer", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public Customer createCustomer(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "firstName")
        String firstName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "lastName")
        String lastName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "email")
        String email,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "password")
        String password,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "notes")
        String notes);

    /**
     * 
     * @param lastName
     * @param email
     * @param notes
     * @param firstName
     * @param customerID
     * @param websiteConfigID
     * @param password
     * @return
     *     returns com.ticketnetwork.webservices2.Customer
     */
    @WebMethod(operationName = "UpdateCustomer")
    @WebResult(name = "Customer", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public Customer updateCustomer(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "customerID")
        String customerID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "firstName")
        String firstName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "lastName")
        String lastName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "email")
        String email,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "password")
        String password,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "notes")
        String notes);

    /**
     * 
     * @param email
     * @param websiteConfigID
     * @param password
     * @return
     *     returns int
     */
    @WebMethod(operationName = "GetCustomerID")
    @WebResult(name = "int", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public int getCustomerID(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "email")
        String email,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "password")
        String password);

    /**
     * 
     * @param customerID
     * @param websiteConfigID
     * @param ticketRequestID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfRequest
     */
    @WebMethod(operationName = "GetRequest")
    @WebResult(name = "ArrayOfRequest", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public ArrayOfRequest getRequest(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "customerID")
        String customerID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ticketRequestID")
        String ticketRequestID);

    /**
     * 
     * @param creditCardID
     * @param specialInstructions
     * @param referralSourceDetails
     * @param customerIPAddress
     * @param acceptAlternate
     * @param overridePrice
     * @param shippingMethodID
     * @param ticketQuantity
     * @param websiteConfigID
     * @param customerID
     * @param promoCode
     * @param ticketGroupID
     * @param referralSourceID
     * @return
     *     returns com.ticketnetwork.webservices2.RequestConfirmation
     */
    @WebMethod(operationName = "CreateRequest")
    @WebResult(name = "RequestConfirmation", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public RequestConfirmation createRequest(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "customerID")
        String customerID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "creditCardID")
        String creditCardID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ticketGroupID")
        String ticketGroupID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ticketQuantity")
        String ticketQuantity,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "shippingMethodID")
        String shippingMethodID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "specialInstructions")
        String specialInstructions,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "promoCode")
        String promoCode,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "acceptAlternate")
        String acceptAlternate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "referralSourceID")
        String referralSourceID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "referralSourceDetails")
        String referralSourceDetails,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "overridePrice")
        String overridePrice,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "customerIPAddress")
        String customerIPAddress);

    /**
     * 
     * @param eventID
     * @param sessionID
     * @param price
     * @param websiteConfigID
     * @param ticketGroupID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreateTamperProofQueryString")
    @WebResult(name = "string", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public String createTamperProofQueryString(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ticketGroupID")
        String ticketGroupID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "eventID")
        String eventID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "price")
        String price,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "sessionID")
        String sessionID);

    /**
     * 
     * @param websiteConfigID
     * @param ticketRequestID
     * @return
     *     returns com.ticketnetwork.webservices2.RequestStatus
     */
    @WebMethod(operationName = "GetRequestStatus")
    @WebResult(name = "RequestStatus", targetNamespace = "http://webservices2.ticketnetwork.com", partName = "Body")
    public RequestStatus getRequestStatus(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ticketRequestID")
        String ticketRequestID);

}
