
package com.ticketnetwork.webservices2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TNServicesStringInputsSoap", targetNamespace = "http://webservices2.ticketnetwork.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TNServicesStringInputsSoap {


    /**
     * 
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfCreditCardType
     */
    @WebMethod(operationName = "GetCreditCardTypes", action = "http://webservices2.ticketnetwork.com/GetCreditCardTypes")
    @WebResult(name = "GetCreditCardTypesResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "GetCreditCardTypes", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetCreditCardTypes")
    @ResponseWrapper(localName = "GetCreditCardTypesResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetCreditCardTypesResponse")
    public ArrayOfCreditCardType getCreditCardTypes(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID);

    /**
     * 
     * @param websiteConfigID
     * @param ticketGroupID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfCreditCardType
     */
    @WebMethod(operationName = "GetAcceptedCreditCardTypes", action = "http://webservices2.ticketnetwork.com/GetAcceptedCreditCardTypes")
    @WebResult(name = "GetAcceptedCreditCardTypesResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "GetAcceptedCreditCardTypes", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetAcceptedCreditCardTypes")
    @ResponseWrapper(localName = "GetAcceptedCreditCardTypesResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetAcceptedCreditCardTypesResponse")
    public ArrayOfCreditCardType getAcceptedCreditCardTypes(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID,
        @WebParam(name = "ticketGroupID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String ticketGroupID);

    /**
     * 
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfCategory
     */
    @WebMethod(operationName = "GetCategories", action = "http://webservices2.ticketnetwork.com/GetCategories")
    @WebResult(name = "GetCategoriesResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "GetCategories", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetCategories")
    @ResponseWrapper(localName = "GetCategoriesResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetCategoriesResponse")
    public ArrayOfCategory getCategories(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID);

    /**
     * 
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfCategory
     */
    @WebMethod(operationName = "GetCategoriesMasterList", action = "http://webservices2.ticketnetwork.com/GetCategoriesMasterList")
    @WebResult(name = "GetCategoriesMasterListResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "GetCategoriesMasterList", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetCategoriesMasterList")
    @ResponseWrapper(localName = "GetCategoriesMasterListResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetCategoriesMasterListResponse")
    public ArrayOfCategory getCategoriesMasterList(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID);

    /**
     * 
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfCountry
     */
    @WebMethod(operationName = "GetCountries", action = "http://webservices2.ticketnetwork.com/GetCountries")
    @WebResult(name = "GetCountriesResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "GetCountries", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetCountries")
    @ResponseWrapper(localName = "GetCountriesResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetCountriesResponse")
    public ArrayOfCountry getCountries(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID);

    /**
     * 
     * @param countryID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.Country
     */
    @WebMethod(operationName = "GetCountryByID", action = "http://webservices2.ticketnetwork.com/GetCountryByID")
    @WebResult(name = "GetCountryByIDResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "GetCountryByID", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetCountryByID")
    @ResponseWrapper(localName = "GetCountryByIDResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetCountryByIDResponse")
    public Country getCountryByID(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID,
        @WebParam(name = "countryID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String countryID);

    /**
     * 
     * @param performerName
     * @param eventDate
     * @param grandchildCategoryID
     * @param onlyMine
     * @param sortDescending
     * @param endDate
     * @param beginDate
     * @param performerID
     * @param stateProvince
     * @param nearZip
     * @param websiteConfigID
     * @param venueName
     * @param numberOfEvents
     * @param noPerformers
     * @param parentCategoryID
     * @param childCategoryID
     * @param lowPrice
     * @param stateProvinceID
     * @param eventID
     * @param sortColumn
     * @param eventName
     * @param modificationDate
     * @param highPrice
     * @param cityZip
     * @param mandatoryCreditCard
     * @param venueID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfEvent
     */
    @WebMethod(operationName = "GetEvents", action = "http://webservices2.ticketnetwork.com/GetEvents")
    @WebResult(name = "GetEventsResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "GetEvents", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetEvents")
    @ResponseWrapper(localName = "GetEventsResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetEventsResponse")
    public ArrayOfEvent getEvents(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID,
        @WebParam(name = "numberOfEvents", targetNamespace = "http://webservices2.ticketnetwork.com")
        String numberOfEvents,
        @WebParam(name = "eventID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String eventID,
        @WebParam(name = "eventName", targetNamespace = "http://webservices2.ticketnetwork.com")
        String eventName,
        @WebParam(name = "eventDate", targetNamespace = "http://webservices2.ticketnetwork.com")
        String eventDate,
        @WebParam(name = "beginDate", targetNamespace = "http://webservices2.ticketnetwork.com")
        String beginDate,
        @WebParam(name = "endDate", targetNamespace = "http://webservices2.ticketnetwork.com")
        String endDate,
        @WebParam(name = "venueID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String venueID,
        @WebParam(name = "venueName", targetNamespace = "http://webservices2.ticketnetwork.com")
        String venueName,
        @WebParam(name = "stateProvince", targetNamespace = "http://webservices2.ticketnetwork.com")
        String stateProvince,
        @WebParam(name = "stateProvinceID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String stateProvinceID,
        @WebParam(name = "cityZip", targetNamespace = "http://webservices2.ticketnetwork.com")
        String cityZip,
        @WebParam(name = "nearZip", targetNamespace = "http://webservices2.ticketnetwork.com")
        String nearZip,
        @WebParam(name = "parentCategoryID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String parentCategoryID,
        @WebParam(name = "childCategoryID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String childCategoryID,
        @WebParam(name = "grandchildCategoryID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String grandchildCategoryID,
        @WebParam(name = "performerID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String performerID,
        @WebParam(name = "performerName", targetNamespace = "http://webservices2.ticketnetwork.com")
        String performerName,
        @WebParam(name = "noPerformers", targetNamespace = "http://webservices2.ticketnetwork.com")
        String noPerformers,
        @WebParam(name = "lowPrice", targetNamespace = "http://webservices2.ticketnetwork.com")
        String lowPrice,
        @WebParam(name = "highPrice", targetNamespace = "http://webservices2.ticketnetwork.com")
        String highPrice,
        @WebParam(name = "sortColumn", targetNamespace = "http://webservices2.ticketnetwork.com")
        String sortColumn,
        @WebParam(name = "sortDescending", targetNamespace = "http://webservices2.ticketnetwork.com")
        String sortDescending,
        @WebParam(name = "mandatoryCreditCard", targetNamespace = "http://webservices2.ticketnetwork.com")
        String mandatoryCreditCard,
        @WebParam(name = "modificationDate", targetNamespace = "http://webservices2.ticketnetwork.com")
        String modificationDate,
        @WebParam(name = "onlyMine", targetNamespace = "http://webservices2.ticketnetwork.com")
        String onlyMine);

    /**
     * 
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfEventPerformer
     */
    @WebMethod(operationName = "GetEventPerformers", action = "http://webservices2.ticketnetwork.com/GetEventPerformers")
    @WebResult(name = "GetEventPerformersResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "GetEventPerformers", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetEventPerformers")
    @ResponseWrapper(localName = "GetEventPerformersResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetEventPerformersResponse")
    public ArrayOfEventPerformer getEventPerformers(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID);

    /**
     * 
     * @param grandchildCategoryID
     * @param hasEvent
     * @param parentCategoryID
     * @param childCategoryID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfPerformer
     */
    @WebMethod(operationName = "GetPerformerByCategory", action = "http://webservices2.ticketnetwork.com/GetPerformerByCategory")
    @WebResult(name = "GetPerformerByCategoryResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "GetPerformerByCategory", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetPerformerByCategory")
    @ResponseWrapper(localName = "GetPerformerByCategoryResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetPerformerByCategoryResponse")
    public ArrayOfPerformer getPerformerByCategory(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID,
        @WebParam(name = "parentCategoryID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String parentCategoryID,
        @WebParam(name = "childCategoryID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String childCategoryID,
        @WebParam(name = "grandchildCategoryID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String grandchildCategoryID,
        @WebParam(name = "hasEvent", targetNamespace = "http://webservices2.ticketnetwork.com")
        String hasEvent);

    /**
     * 
     * @param websiteConfigID
     * @param promoCode
     * @return
     *     returns com.ticketnetwork.webservices2.Promo
     */
    @WebMethod(operationName = "GetPromo", action = "http://webservices2.ticketnetwork.com/GetPromo")
    @WebResult(name = "GetPromoResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "GetPromo", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetPromo")
    @ResponseWrapper(localName = "GetPromoResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetPromoResponse")
    public Promo getPromo(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID,
        @WebParam(name = "promoCode", targetNamespace = "http://webservices2.ticketnetwork.com")
        String promoCode);

    /**
     * 
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfReferralType
     */
    @WebMethod(operationName = "GetReferralTypes", action = "http://webservices2.ticketnetwork.com/GetReferralTypes")
    @WebResult(name = "GetReferralTypesResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "GetReferralTypes", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetReferralTypes")
    @ResponseWrapper(localName = "GetReferralTypesResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetReferralTypesResponse")
    public ArrayOfReferralType getReferralTypes(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID);

    /**
     * 
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfAddressType
     */
    @WebMethod(operationName = "GetAddressTypes", action = "http://webservices2.ticketnetwork.com/GetAddressTypes")
    @WebResult(name = "GetAddressTypesResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "GetAddressTypes", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetAddressTypes")
    @ResponseWrapper(localName = "GetAddressTypesResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetAddressTypesResponse")
    public ArrayOfAddressType getAddressTypes(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID);

    /**
     * 
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfPhoneType
     */
    @WebMethod(operationName = "GetPhoneTypes", action = "http://webservices2.ticketnetwork.com/GetPhoneTypes")
    @WebResult(name = "GetPhoneTypesResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "GetPhoneTypes", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetPhoneTypes")
    @ResponseWrapper(localName = "GetPhoneTypesResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetPhoneTypesResponse")
    public ArrayOfPhoneType getPhoneTypes(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID);

    /**
     * 
     * @param websiteConfigID
     * @param ticketGroupID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfShippingMethod
     */
    @WebMethod(operationName = "GetShippingMethods", action = "http://webservices2.ticketnetwork.com/GetShippingMethods")
    @WebResult(name = "GetShippingMethodsResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "GetShippingMethods", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetShippingMethods")
    @ResponseWrapper(localName = "GetShippingMethodsResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetShippingMethodsResponse")
    public ArrayOfShippingMethod getShippingMethods(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID,
        @WebParam(name = "ticketGroupID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String ticketGroupID);

    /**
     * 
     * @param parentCategoryID
     * @param childCategoryID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfCategory
     */
    @WebMethod(operationName = "GetSublevelCategories", action = "http://webservices2.ticketnetwork.com/GetSublevelCategories")
    @WebResult(name = "GetSublevelCategoriesResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "GetSublevelCategories", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetSublevelCategories")
    @ResponseWrapper(localName = "GetSublevelCategoriesResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetSublevelCategoriesResponse")
    public ArrayOfCategory getSublevelCategories(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID,
        @WebParam(name = "parentCategoryID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String parentCategoryID,
        @WebParam(name = "childCategoryID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String childCategoryID);

    /**
     * 
     * @param sortColumn
     * @param eventID
     * @param numberOfRecords
     * @param sortDescending
     * @param requestedSplit
     * @param websiteConfigID
     * @param highPrice
     * @param lowPrice
     * @param mandatoryCreditCard
     * @param ticketGroupID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfTicketGroup
     */
    @WebMethod(operationName = "GetTickets", action = "http://webservices2.ticketnetwork.com/GetTickets")
    @WebResult(name = "GetTicketsResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "GetTickets", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetTickets")
    @ResponseWrapper(localName = "GetTicketsResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetTicketsResponse")
    public ArrayOfTicketGroup getTickets(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID,
        @WebParam(name = "numberOfRecords", targetNamespace = "http://webservices2.ticketnetwork.com")
        String numberOfRecords,
        @WebParam(name = "eventID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String eventID,
        @WebParam(name = "lowPrice", targetNamespace = "http://webservices2.ticketnetwork.com")
        String lowPrice,
        @WebParam(name = "highPrice", targetNamespace = "http://webservices2.ticketnetwork.com")
        String highPrice,
        @WebParam(name = "ticketGroupID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String ticketGroupID,
        @WebParam(name = "mandatoryCreditCard", targetNamespace = "http://webservices2.ticketnetwork.com")
        String mandatoryCreditCard,
        @WebParam(name = "requestedSplit", targetNamespace = "http://webservices2.ticketnetwork.com")
        String requestedSplit,
        @WebParam(name = "sortColumn", targetNamespace = "http://webservices2.ticketnetwork.com")
        String sortColumn,
        @WebParam(name = "sortDescending", targetNamespace = "http://webservices2.ticketnetwork.com")
        String sortDescending);

    /**
     * 
     * @param websiteConfigID
     * @param venueID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfVenue
     */
    @WebMethod(operationName = "GetVenue", action = "http://webservices2.ticketnetwork.com/GetVenue")
    @WebResult(name = "GetVenueResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "GetVenue", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetVenue")
    @ResponseWrapper(localName = "GetVenueResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetVenueResponse")
    public ArrayOfVenue getVenue(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID,
        @WebParam(name = "venueID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String venueID);

    /**
     * 
     * @param websiteConfigID
     * @param venueID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfVenueConfiguration
     */
    @WebMethod(operationName = "GetVenueConfigurations", action = "http://webservices2.ticketnetwork.com/GetVenueConfigurations")
    @WebResult(name = "GetVenueConfigurationsResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "GetVenueConfigurations", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetVenueConfigurations")
    @ResponseWrapper(localName = "GetVenueConfigurationsResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetVenueConfigurationsResponse")
    public ArrayOfVenueConfiguration getVenueConfigurations(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID,
        @WebParam(name = "venueID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String venueID);

    /**
     * 
     * @param grandchildCategoryID
     * @param numReturned
     * @param parentCategoryID
     * @param childCategoryID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfPerformerPercent
     */
    @WebMethod(operationName = "GetHighInventoryPerformers", action = "http://webservices2.ticketnetwork.com/GetHighInventoryPerformers")
    @WebResult(name = "GetHighInventoryPerformersResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "GetHighInventoryPerformers", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetHighInventoryPerformers")
    @ResponseWrapper(localName = "GetHighInventoryPerformersResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetHighInventoryPerformersResponse")
    public ArrayOfPerformerPercent getHighInventoryPerformers(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID,
        @WebParam(name = "numReturned", targetNamespace = "http://webservices2.ticketnetwork.com")
        String numReturned,
        @WebParam(name = "parentCategoryID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String parentCategoryID,
        @WebParam(name = "childCategoryID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String childCategoryID,
        @WebParam(name = "grandchildCategoryID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String grandchildCategoryID);

    /**
     * 
     * @param grandchildCategoryID
     * @param numReturned
     * @param parentCategoryID
     * @param childCategoryID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfPerformerPercent
     */
    @WebMethod(operationName = "GetHighSalesPerformers", action = "http://webservices2.ticketnetwork.com/GetHighSalesPerformers")
    @WebResult(name = "GetHighSalesPerformersResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "GetHighSalesPerformers", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetHighSalesPerformers")
    @ResponseWrapper(localName = "GetHighSalesPerformersResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetHighSalesPerformersResponse")
    public ArrayOfPerformerPercent getHighSalesPerformers(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID,
        @WebParam(name = "numReturned", targetNamespace = "http://webservices2.ticketnetwork.com")
        String numReturned,
        @WebParam(name = "parentCategoryID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String parentCategoryID,
        @WebParam(name = "childCategoryID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String childCategoryID,
        @WebParam(name = "grandchildCategoryID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String grandchildCategoryID);

    /**
     * 
     * @param creditCardID
     * @param creditCardTypeID
     * @param customerID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfCreditCard
     */
    @WebMethod(operationName = "GetCreditCard", action = "http://webservices2.ticketnetwork.com/GetCreditCard")
    @WebResult(name = "GetCreditCardResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "GetCreditCard", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetCreditCard")
    @ResponseWrapper(localName = "GetCreditCardResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetCreditCardResponse")
    public ArrayOfCreditCard getCreditCard(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID,
        @WebParam(name = "creditCardID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String creditCardID,
        @WebParam(name = "customerID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String customerID,
        @WebParam(name = "creditCardTypeID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String creditCardTypeID);

    /**
     * 
     * @param secNumber
     * @param expiresMonth
     * @param number
     * @param customerID
     * @param websiteConfigID
     * @param nameDisplayed
     * @param expiresYear
     * @return
     *     returns com.ticketnetwork.webservices2.CreditCard
     */
    @WebMethod(operationName = "CreateCreditCard", action = "http://webservices2.ticketnetwork.com/CreateCreditCard")
    @WebResult(name = "CreateCreditCardResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "CreateCreditCard", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.CreateCreditCard")
    @ResponseWrapper(localName = "CreateCreditCardResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.CreateCreditCardResponse")
    public CreditCard createCreditCard(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID,
        @WebParam(name = "customerID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String customerID,
        @WebParam(name = "number", targetNamespace = "http://webservices2.ticketnetwork.com")
        String number,
        @WebParam(name = "secNumber", targetNamespace = "http://webservices2.ticketnetwork.com")
        String secNumber,
        @WebParam(name = "nameDisplayed", targetNamespace = "http://webservices2.ticketnetwork.com")
        String nameDisplayed,
        @WebParam(name = "expiresMonth", targetNamespace = "http://webservices2.ticketnetwork.com")
        String expiresMonth,
        @WebParam(name = "expiresYear", targetNamespace = "http://webservices2.ticketnetwork.com")
        String expiresYear);

    /**
     * 
     * @param secNumber
     * @param expiresMonth
     * @param number
     * @param customerID
     * @param websiteConfigID
     * @param nameDisplayed
     * @param expiresYear
     * @return
     *     returns com.ticketnetwork.webservices2.CreditCard
     */
    @WebMethod(operationName = "UpdateCreditCard", action = "http://webservices2.ticketnetwork.com/UpdateCreditCard")
    @WebResult(name = "UpdateCreditCardResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "UpdateCreditCard", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.UpdateCreditCard")
    @ResponseWrapper(localName = "UpdateCreditCardResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.UpdateCreditCardResponse")
    public CreditCard updateCreditCard(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID,
        @WebParam(name = "customerID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String customerID,
        @WebParam(name = "number", targetNamespace = "http://webservices2.ticketnetwork.com")
        String number,
        @WebParam(name = "secNumber", targetNamespace = "http://webservices2.ticketnetwork.com")
        String secNumber,
        @WebParam(name = "nameDisplayed", targetNamespace = "http://webservices2.ticketnetwork.com")
        String nameDisplayed,
        @WebParam(name = "expiresMonth", targetNamespace = "http://webservices2.ticketnetwork.com")
        String expiresMonth,
        @WebParam(name = "expiresYear", targetNamespace = "http://webservices2.ticketnetwork.com")
        String expiresYear);

    /**
     * 
     * @param number
     * @param websiteConfigID
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "IsCreditCardNumberValid", action = "http://webservices2.ticketnetwork.com/IsCreditCardNumberValid")
    @WebResult(name = "IsCreditCardNumberValidResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "IsCreditCardNumberValid", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.IsCreditCardNumberValid")
    @ResponseWrapper(localName = "IsCreditCardNumberValidResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.IsCreditCardNumberValidResponse")
    public boolean isCreditCardNumberValid(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID,
        @WebParam(name = "number", targetNamespace = "http://webservices2.ticketnetwork.com")
        String number);

    /**
     * 
     * @param phoneTypeID
     * @param phoneID
     * @param customerID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfPhone
     */
    @WebMethod(operationName = "GetPhone", action = "http://webservices2.ticketnetwork.com/GetPhone")
    @WebResult(name = "GetPhoneResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "GetPhone", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetPhone")
    @ResponseWrapper(localName = "GetPhoneResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetPhoneResponse")
    public ArrayOfPhone getPhone(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID,
        @WebParam(name = "phoneID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String phoneID,
        @WebParam(name = "customerID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String customerID,
        @WebParam(name = "phoneTypeID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String phoneTypeID);

    /**
     * 
     * @param phoneNumber
     * @param displayOrder
     * @param phoneTypeID
     * @param customerID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.Phone
     */
    @WebMethod(operationName = "CreatePhone", action = "http://webservices2.ticketnetwork.com/CreatePhone")
    @WebResult(name = "CreatePhoneResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "CreatePhone", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.CreatePhone")
    @ResponseWrapper(localName = "CreatePhoneResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.CreatePhoneResponse")
    public Phone createPhone(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID,
        @WebParam(name = "customerID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String customerID,
        @WebParam(name = "phoneNumber", targetNamespace = "http://webservices2.ticketnetwork.com")
        String phoneNumber,
        @WebParam(name = "phoneTypeID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String phoneTypeID,
        @WebParam(name = "displayOrder", targetNamespace = "http://webservices2.ticketnetwork.com")
        String displayOrder);

    /**
     * 
     * @param phoneNumber
     * @param displayOrder
     * @param phoneTypeID
     * @param customerID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.Phone
     */
    @WebMethod(operationName = "UpdatePhone", action = "http://webservices2.ticketnetwork.com/UpdatePhone")
    @WebResult(name = "UpdatePhoneResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "UpdatePhone", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.UpdatePhone")
    @ResponseWrapper(localName = "UpdatePhoneResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.UpdatePhoneResponse")
    public Phone updatePhone(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID,
        @WebParam(name = "customerID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String customerID,
        @WebParam(name = "phoneNumber", targetNamespace = "http://webservices2.ticketnetwork.com")
        String phoneNumber,
        @WebParam(name = "phoneTypeID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String phoneTypeID,
        @WebParam(name = "displayOrder", targetNamespace = "http://webservices2.ticketnetwork.com")
        String displayOrder);

    /**
     * 
     * @param addressTypeID
     * @param customerID
     * @param addressID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfAddress
     */
    @WebMethod(operationName = "GetAddress", action = "http://webservices2.ticketnetwork.com/GetAddress")
    @WebResult(name = "GetAddressResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "GetAddress", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetAddress")
    @ResponseWrapper(localName = "GetAddressResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetAddressResponse")
    public ArrayOfAddress getAddress(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID,
        @WebParam(name = "addressID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String addressID,
        @WebParam(name = "customerID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String customerID,
        @WebParam(name = "addressTypeID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String addressTypeID);

    /**
     * 
     * @param addressTypeID
     * @param stateProvAbbr
     * @param street2
     * @param street1
     * @param countryID
     * @param contactName
     * @param zipCode
     * @param customerID
     * @param websiteConfigID
     * @param country
     * @param city
     * @return
     *     returns com.ticketnetwork.webservices2.Address
     */
    @WebMethod(operationName = "CreateAddress", action = "http://webservices2.ticketnetwork.com/CreateAddress")
    @WebResult(name = "CreateAddressResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "CreateAddress", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.CreateAddress")
    @ResponseWrapper(localName = "CreateAddressResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.CreateAddressResponse")
    public Address createAddress(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID,
        @WebParam(name = "customerID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String customerID,
        @WebParam(name = "contactName", targetNamespace = "http://webservices2.ticketnetwork.com")
        String contactName,
        @WebParam(name = "street1", targetNamespace = "http://webservices2.ticketnetwork.com")
        String street1,
        @WebParam(name = "street2", targetNamespace = "http://webservices2.ticketnetwork.com")
        String street2,
        @WebParam(name = "city", targetNamespace = "http://webservices2.ticketnetwork.com")
        String city,
        @WebParam(name = "zipCode", targetNamespace = "http://webservices2.ticketnetwork.com")
        String zipCode,
        @WebParam(name = "stateProvAbbr", targetNamespace = "http://webservices2.ticketnetwork.com")
        String stateProvAbbr,
        @WebParam(name = "country", targetNamespace = "http://webservices2.ticketnetwork.com")
        String country,
        @WebParam(name = "countryID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String countryID,
        @WebParam(name = "addressTypeID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String addressTypeID);

    /**
     * 
     * @param addressTypeID
     * @param stateProvAbbr
     * @param street2
     * @param street1
     * @param countryID
     * @param contactName
     * @param zipCode
     * @param customerID
     * @param websiteConfigID
     * @param country
     * @param city
     * @return
     *     returns com.ticketnetwork.webservices2.Address
     */
    @WebMethod(operationName = "UpdateAddress", action = "http://webservices2.ticketnetwork.com/UpdateAddress")
    @WebResult(name = "UpdateAddressResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "UpdateAddress", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.UpdateAddress")
    @ResponseWrapper(localName = "UpdateAddressResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.UpdateAddressResponse")
    public Address updateAddress(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID,
        @WebParam(name = "customerID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String customerID,
        @WebParam(name = "contactName", targetNamespace = "http://webservices2.ticketnetwork.com")
        String contactName,
        @WebParam(name = "street1", targetNamespace = "http://webservices2.ticketnetwork.com")
        String street1,
        @WebParam(name = "street2", targetNamespace = "http://webservices2.ticketnetwork.com")
        String street2,
        @WebParam(name = "city", targetNamespace = "http://webservices2.ticketnetwork.com")
        String city,
        @WebParam(name = "zipCode", targetNamespace = "http://webservices2.ticketnetwork.com")
        String zipCode,
        @WebParam(name = "stateProvAbbr", targetNamespace = "http://webservices2.ticketnetwork.com")
        String stateProvAbbr,
        @WebParam(name = "country", targetNamespace = "http://webservices2.ticketnetwork.com")
        String country,
        @WebParam(name = "countryID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String countryID,
        @WebParam(name = "addressTypeID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String addressTypeID);

    /**
     * 
     * @param customerID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.webservices2.Customer
     */
    @WebMethod(operationName = "GetCustomerByID", action = "http://webservices2.ticketnetwork.com/GetCustomerByID")
    @WebResult(name = "GetCustomerByIDResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "GetCustomerByID", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetCustomerByID")
    @ResponseWrapper(localName = "GetCustomerByIDResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetCustomerByIDResponse")
    public Customer getCustomerByID(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID,
        @WebParam(name = "customerID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String customerID);

    /**
     * 
     * @param lastName
     * @param email
     * @param notes
     * @param firstName
     * @param websiteConfigID
     * @param password
     * @return
     *     returns com.ticketnetwork.webservices2.Customer
     */
    @WebMethod(operationName = "CreateCustomer", action = "http://webservices2.ticketnetwork.com/CreateCustomer")
    @WebResult(name = "CreateCustomerResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "CreateCustomer", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.CreateCustomer")
    @ResponseWrapper(localName = "CreateCustomerResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.CreateCustomerResponse")
    public Customer createCustomer(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID,
        @WebParam(name = "firstName", targetNamespace = "http://webservices2.ticketnetwork.com")
        String firstName,
        @WebParam(name = "lastName", targetNamespace = "http://webservices2.ticketnetwork.com")
        String lastName,
        @WebParam(name = "email", targetNamespace = "http://webservices2.ticketnetwork.com")
        String email,
        @WebParam(name = "password", targetNamespace = "http://webservices2.ticketnetwork.com")
        String password,
        @WebParam(name = "notes", targetNamespace = "http://webservices2.ticketnetwork.com")
        String notes);

    /**
     * 
     * @param lastName
     * @param email
     * @param notes
     * @param firstName
     * @param customerID
     * @param websiteConfigID
     * @param password
     * @return
     *     returns com.ticketnetwork.webservices2.Customer
     */
    @WebMethod(operationName = "UpdateCustomer", action = "http://webservices2.ticketnetwork.com/UpdateCustomer")
    @WebResult(name = "UpdateCustomerResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "UpdateCustomer", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.UpdateCustomer")
    @ResponseWrapper(localName = "UpdateCustomerResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.UpdateCustomerResponse")
    public Customer updateCustomer(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID,
        @WebParam(name = "customerID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String customerID,
        @WebParam(name = "firstName", targetNamespace = "http://webservices2.ticketnetwork.com")
        String firstName,
        @WebParam(name = "lastName", targetNamespace = "http://webservices2.ticketnetwork.com")
        String lastName,
        @WebParam(name = "email", targetNamespace = "http://webservices2.ticketnetwork.com")
        String email,
        @WebParam(name = "password", targetNamespace = "http://webservices2.ticketnetwork.com")
        String password,
        @WebParam(name = "notes", targetNamespace = "http://webservices2.ticketnetwork.com")
        String notes);

    /**
     * 
     * @param email
     * @param websiteConfigID
     * @param password
     * @return
     *     returns int
     */
    @WebMethod(operationName = "GetCustomerID", action = "http://webservices2.ticketnetwork.com/GetCustomerID")
    @WebResult(name = "GetCustomerIDResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "GetCustomerID", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetCustomerID")
    @ResponseWrapper(localName = "GetCustomerIDResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetCustomerIDResponse")
    public int getCustomerID(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID,
        @WebParam(name = "email", targetNamespace = "http://webservices2.ticketnetwork.com")
        String email,
        @WebParam(name = "password", targetNamespace = "http://webservices2.ticketnetwork.com")
        String password);

    /**
     * 
     * @param customerID
     * @param websiteConfigID
     * @param ticketRequestID
     * @return
     *     returns com.ticketnetwork.webservices2.ArrayOfRequest
     */
    @WebMethod(operationName = "GetRequest", action = "http://webservices2.ticketnetwork.com/GetRequest")
    @WebResult(name = "GetRequestResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "GetRequest", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetRequest")
    @ResponseWrapper(localName = "GetRequestResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetRequestResponse")
    public ArrayOfRequest getRequest(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID,
        @WebParam(name = "customerID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String customerID,
        @WebParam(name = "ticketRequestID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String ticketRequestID);

    /**
     * 
     * @param creditCardID
     * @param specialInstructions
     * @param referralSourceDetails
     * @param customerIPAddress
     * @param acceptAlternate
     * @param overridePrice
     * @param shippingMethodID
     * @param ticketQuantity
     * @param websiteConfigID
     * @param customerID
     * @param promoCode
     * @param ticketGroupID
     * @param referralSourceID
     * @return
     *     returns com.ticketnetwork.webservices2.RequestConfirmation
     */
    @WebMethod(operationName = "CreateRequest", action = "http://webservices2.ticketnetwork.com/CreateRequest")
    @WebResult(name = "CreateRequestResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "CreateRequest", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.CreateRequest")
    @ResponseWrapper(localName = "CreateRequestResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.CreateRequestResponse")
    public RequestConfirmation createRequest(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID,
        @WebParam(name = "customerID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String customerID,
        @WebParam(name = "creditCardID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String creditCardID,
        @WebParam(name = "ticketGroupID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String ticketGroupID,
        @WebParam(name = "ticketQuantity", targetNamespace = "http://webservices2.ticketnetwork.com")
        String ticketQuantity,
        @WebParam(name = "shippingMethodID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String shippingMethodID,
        @WebParam(name = "specialInstructions", targetNamespace = "http://webservices2.ticketnetwork.com")
        String specialInstructions,
        @WebParam(name = "promoCode", targetNamespace = "http://webservices2.ticketnetwork.com")
        String promoCode,
        @WebParam(name = "acceptAlternate", targetNamespace = "http://webservices2.ticketnetwork.com")
        String acceptAlternate,
        @WebParam(name = "referralSourceID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String referralSourceID,
        @WebParam(name = "referralSourceDetails", targetNamespace = "http://webservices2.ticketnetwork.com")
        String referralSourceDetails,
        @WebParam(name = "overridePrice", targetNamespace = "http://webservices2.ticketnetwork.com")
        String overridePrice,
        @WebParam(name = "customerIPAddress", targetNamespace = "http://webservices2.ticketnetwork.com")
        String customerIPAddress);

    /**
     * 
     * @param eventID
     * @param sessionID
     * @param price
     * @param websiteConfigID
     * @param ticketGroupID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreateTamperProofQueryString", action = "http://webservices2.ticketnetwork.com/CreateTamperProofQueryString")
    @WebResult(name = "CreateTamperProofQueryStringResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "CreateTamperProofQueryString", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.CreateTamperProofQueryString")
    @ResponseWrapper(localName = "CreateTamperProofQueryStringResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.CreateTamperProofQueryStringResponse")
    public String createTamperProofQueryString(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID,
        @WebParam(name = "ticketGroupID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String ticketGroupID,
        @WebParam(name = "eventID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String eventID,
        @WebParam(name = "price", targetNamespace = "http://webservices2.ticketnetwork.com")
        String price,
        @WebParam(name = "sessionID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String sessionID);

    /**
     * 
     * @param websiteConfigID
     * @param ticketRequestID
     * @return
     *     returns com.ticketnetwork.webservices2.RequestStatus
     */
    @WebMethod(operationName = "GetRequestStatus", action = "http://webservices2.ticketnetwork.com/GetRequestStatus")
    @WebResult(name = "GetRequestStatusResult", targetNamespace = "http://webservices2.ticketnetwork.com")
    @RequestWrapper(localName = "GetRequestStatus", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetRequestStatus")
    @ResponseWrapper(localName = "GetRequestStatusResponse", targetNamespace = "http://webservices2.ticketnetwork.com", className = "com.ticketnetwork.webservices2.GetRequestStatusResponse")
    public RequestStatus getRequestStatus(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String websiteConfigID,
        @WebParam(name = "ticketRequestID", targetNamespace = "http://webservices2.ticketnetwork.com")
        String ticketRequestID);

}
